//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.18 at 10:18:08 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.abrasf.org.br/ABRASF/arquivos/nfse.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nfe.entidades.layoutnfse;
